# Site settings
title: Fonzie‘s Blog
header-img: img/home-bg.jpg
email: lauhonyeung@gmail.com
description: "我见过最高尚的兽人，也见过最卑鄙的人类。"
baseurl: ""
url: "fonzie.github.io"
twitter_username: lauhonyeung
github_username:  fonzieyang
facebook_page:  100002189774636
weibo_username: lauhonyeung

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
