# Site settings
title: Fonzie‘s Blog
header-img: img/home-bg.jpg
email: lauhonyeung@gmail.com
description: "make it Fun and it will get Done."
baseurl: ""
url: ""
twitter_username: lauhonyeung
github_username:  fonzieyang
facebook_page:  100002189774636
weibo_username: lauhonyeung
linkedin_id: 321914505

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
