# Site settings
title: Fonzie‘s Blog
header-img: img/home-bg.jpg
email: lauhonyeung@gmail.com
description: "make it Fun and it will get Done."
baseurl: ""
url: ""
twitter_username: lauhonyeung
github_username:  fonzieyang
facebook_page:  lauhonyeung
weibo_username: lauhonyeung
linkedin_username: lauhonyeung

# Build settings
pygments: true
markdown: kramdown
highlighter: pygments
permalink: /:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
