# Site settings
title: 瀚阳的博客
header-img: img/sztx_raining.jpg
email: lauhonyeung@gmail.com
description: "关于游戏、编程、技术"
baseurl: ""
url: ""
twitter_username: lauhonyeung
github_username:  fonzieyang
facebook_page:  lauhonyeung
weibo_username: lauhonyeung
linkedin_username: lauhonyeung
zhihu_username: liu-han-yang

# Build settings
#markdown: kramdown
highlighter: pygments
permalink: /:title
gems: [jekyll-paginate]
paginate_path: "page:num"
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

markdown: redcarpet
redcarpet:
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
